version: "3.4"

networks:
  test_lint:
    external: false

services:
  test_lint:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: yarn next lint
    networks:
      - test_lint
